language: cpp

matrix:
  include:

    # macOS
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: CPPCOMPILER='clang++' CCOMPILER='clang' BUILD_TYPE='Debug'
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: CPPCOMPILER='clang++' CCOMPILER='clang' BUILD_TYPE='Debug'
    - os: osx
      osx_image: xcode10.2
      compiler: clang
      env: CPPCOMPILER='clang++' CCOMPILER='clang' BUILD_TYPE='Debug'
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      env: CPPCOMPILER='clang++' CCOMPILER='clang' BUILD_TYPE='Debug'
    - os: osx
      osx_image: xcode11.5
      compiler: clang
      env: CPPCOMPILER='clang++' CCOMPILER='clang' BUILD_TYPE='Debug'
    - os: osx
      osx_image: xcode12u
      compiler: clang
      env: CPPCOMPILER='clang++' CCOMPILER='clang' BUILD_TYPE='Debug'

    # linux
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: [
            'g++-7',
            'libxcb-util0-dev', 
            'libxcb-xkb-dev', 
            'libgtkmm-3.0-dev', 
            'libxcb-cursor-dev', 
            'libxkbcommon-dev', 
            'libxkbcommon-x11-dev',
            'libxcb-keysyms1-dev'
          ]
      env: CPPCOMPILER='g++-7' CCOMPILER='gcc-7' BUILD_TYPE='Debug'

install:
  true

script:
  - export CXX=${CPPCOMPILER}
  - export CC=${CCOMPILER}
  - mkdir -p build
  - cd build
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        cmake -GXcode -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ../vstgui/
    elif [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        cmake -DVSTGUI_STANDALONE=OFF -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ../vstgui/
    fi
  - cmake --build .

